name: Gerrit LLM Reviewer

on:
  push:
    branches: [ main ]

jobs:
  review:
    runs-on: self-hosted


    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Install dependencies
      
      run: |
        python -m venv venv
        venv\Scripts\activate
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Run Gerrit LLM reviewer
      continue-on-error: true  # ✅ CORRECT position
      env:
        GERRIT_USER: ${{ secrets.GERRIT_USER }}
        GERRIT_PASS: ${{ secrets.GERRIT_PASS }}
        GERRIT_URL: ${{ secrets.GERRIT_URL }}
        LLM_API: ${{ secrets.LLM_API }}
      run: |
        echo "🧠 Running Gerrit LLM reviewer..."
        python auto_reviewer.py
